#!/usr/bin/env ruby

if ARGV[0] == "usage"
	puts "  Scheduler:"
	exit
end

# regex for dates t:(mysql formatted date)
date_pattern = /(\s|\A)t:([0-9]{2,4})-([0-1][0-9])-([0-3][0-9])(\s|\z)/

# get the user args
todo_idx = ARGV[1].to_i

# read todo file
all_todos = File.read(ENV['TODO_FILE'])
all_todos = all_todos.split($/)

# grab the todo we're working with
todo = all_todos[todo_idx - 1]

# remove any existing date from todo
todo.gsub!(date_pattern, '')

# replace todo with new todo with no date
command = "#{ENV['TODO_FULL_SH']} replace #{todo_idx} \"#{todo}\""
exec(command)
