# vi: ft=zsh

# my term paths
DROPBOX_BIN=$HOME/Dropbox/bin
HEROKU_BIN=/usr/local/heroku/bin
HOME_BIN=$HOME/bin
NPM_BIN=/usr/local/share/npm/bin
PEAR_BIN=$HOME/pear/bin
RUBY_BIN=/usr/local/opt/ruby/bin
USR_LOCAL_BIN=/usr/local/bin
USR_LOCAL_SBIN=/usr/local/sbin
USR_BIN=/usr/bin
USR_SBIN=/usr/sbin
ROOT_BIN=/bin
ROOT_SBIN=/sbin
X11_BIN=/opt/X11/bin
GIT_BIN=/usr/local/git/bin
VAGRANT_HELPERS=$HOME/Dropbox\ \(CCBHQ\)/Vagrant/.vagrant_helpers

# path
export PATH=$DROPBOX_BIN:$HEROKU_BIN:$HOME_BIN:$NPM_BIN:$PEAR_BIN:$RUBY_BIN:$USR_LOCAL_BIN:$USR_LOCAL_SBIN:$USR_BIN:$USR_SBIN:$ROOT_BIN:$ROOT_SBIN:$X11_BIN:$GIT_BIN

# vagrant helpers
if  [[ -f $VAGRANT_HELPERS ]]
then
  source $VAGRANT_HELPERS
fi

# nvm
export NVM_DIR="$HOME/.nvm"
. "$(brew --prefix nvm)/nvm.sh"
