# zshrc - zsh settings
# Author: Kevin Durbin
# vim: set fdm=marker expandtab ts=2 sw=2 ft=zsh:

# {{{ Exports
export ZSH_HOME=$HOME/dotfiles/zsh
export ZPLUG_HOME=$ZSH_HOME/zplug
export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
export EDITOR='code'
export NVM_DIR="$HOME/.nvm"
export SKIP_RESOURCES=1
# }}}

# {{{ Plugins
source $ZPLUG_HOME/init.zsh

zplug 'zplug/zplug', hook-build:'zplug --self-manage'

zplug "zsh-users/zsh-history-substring-search", defer:3
zplug "zsh-users/zsh-syntax-highlighting", defer:3

zplug "modules/completion", from:prezto
zplug "modules/history", from:prezto

zplug "sharat87/zsh-vim-mode"
zplug "chrissicool/zsh-256color"

zplug "mafredri/zsh-async"
zplug "sindresorhus/pure", use:pure.zsh, as:theme

if ! zplug check; then
  zplug install
fi
zplug load
# }}}

# {{{ Aliases
alias lss="ls -lAhF"
alias c="clear"
alias maketags="ctags --exclude=@.gitignore -R ."
alias weather="curl wttr.in"
alias chrome="/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --remote-debugging-port=9222"
# }}}

# {{{ Config
setopt autocd
# }}}

# {{{ History Search
autoload -U history-search-end
zle -N history-beginning-search-backward-end history-search-end
bindkey "^[[A" history-beginning-search-backward-end
# }}}

# {{{ FZF Options
export FZF_DEFAULT_COMMAND='rg --files'
# }}}

# {{{ Brew Stuff
BREW_PREFIX="$(brew --prefix)"
NVM="$BREW_PREFIX/opt/nvm/nvm.sh"
AUTOJUMP="$BREW_PREFIX/etc/profile.d/autojump.sh"
FZF="$HOME/.fzf.zsh"

[ -s "$NVM" ] && . "$NVM"
[ -s "$AUTOJUMP" ] && . "$AUTOJUMP"
[ -f "$FZF" ] && source "$FZF"
# }}}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
