# zshrc - zsh settings
# Author: Kevin Durbin
# vim: set fdm=marker expandtab ts=2 sw=2 ft=zsh:

# {{{ Exports
export ZSH_HOME=$HOME/dotfiles/zsh
export ZPLUG_HOME=$ZSH_HOME/zplug
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
export EDITOR='vim'
export NVM_DIR="$HOME/.nvm"
# }}}

# {{{ Plugins
source $ZPLUG_HOME/init.zsh

zplug 'zplug/zplug', hook-build:'zplug --self-manage'

zplug "zsh-users/zsh-history-substring-search", defer:3
zplug "zsh-users/zsh-syntax-highlighting", defer:3
zplug "zsh-users/zsh-autosuggestions"

zplug "mafredri/zsh-async"
zplug "sindresorhus/pure", use:pure.zsh, as:theme

zplug "modules/completion", from:prezto
zplug "modules/history", from:prezto

zplug "sharat87/zsh-vim-mode"

if ! zplug check; then
  zplug install
fi
zplug load
# }}}

# {{{ Base16
BASE16_SHELL=$HOME/.config/base16-shell
THEME_FILE=$HOME/.base16_theme
BASE16_PROFILE_HELPER=$BASE16_SHELL/profile_helper.sh

if [ -n "$PS1" ] && [ -s "$BASE16_PROFILE_HELPER" ]
then
  eval "$($BASE16_PROFILE_HELPER)"

  if [ -s "$THEME_FILE" ]
  then
    . "$THEME_FILE"
  else
    _base16 "$BASE16_SHELL/scripts/base16-tomorrow-night.sh" tomorrow-night
  fi
fi
# }}}

# {{{ Aliases
alias lss="colorls -1 -l -a"
alias c="clear"
alias maketags="ctags --exclude=@.gitignore -R ."
alias weather="curl wttr.in"
# }}}

# {{{ Config
setopt autocd
setopt correctall
# }}}

# {{{ History Search
autoload -U history-search-end
zle -N history-beginning-search-backward-end history-search-end
bindkey "^[[A" history-beginning-search-backward-end
# }}}

# {{{ FZF Options
export FZF_DEFAULT_COMMAND='rg --files'
# }}}

# {{{ Brew Stuff
BREW_PREFIX="$(brew --prefix)"
NVM="$BREW_PREFIX/opt/nvm/nvm.sh"
AUTOJUMP="$BREW_PREFIX/etc/profile.d/autojump.sh"
FZF="$HOME/.fzf.zsh"

[ -s "$NVM" ] && . "$NVM"
[ -s "$AUTOJUMP" ] && . "$AUTOJUMP"
[ -f "$FZF" ] && source "$FZF"
# }}}

