# vi: ft=zsh

ZSH=$HOME/dotfiles/zsh

export ZPLUG_HOME=$HOME/.zplug
source $ZPLUG_HOME/init.zsh

# prezto plugins
zplug "modules/completion", from:prezto
zplug "modules/homebrew", from:prezto
zplug "modules/history", from:prezto
zplug "modules/git", from:prezto
zplug "modules/osx", from:prezto

# theme
zplug "mafredri/zsh-async", on:sindresorhus/pure
zplug "sindresorhus/pure", use:pure.zsh

# other
zplug "zsh-users/zsh-syntax-highlighting", nice:10

zplug load

# colorized ls
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
# set my editor
export EDITOR='vim'
# use local php at work for faster test running
export USE_LOCAL_PHP=1

# other aliases to make stuff faster
alias lss="ls -lAF"
alias c="clear"

# history search
bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward

# load nvm
[ -f $HOME/.nvm/nvm.sh ] && source $HOME/.nvm/nvm.sh

# autojump
if hash brew 2>/dev/null; then
  [[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh
fi
